# Generated by Django 4.2.6 on 2025-10-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about_cntact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cntact',
            new_name='Contact',
        ),
    ]
