# Generated by Django 4.2.6 on 2025-10-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_cntact_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlinepurchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='onlinepurchase',
            name='online_movie',
        ),
        migrations.RemoveField(
            model_name='onlinepurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='OnlinePurchase',
        ),
    ]
